    const DASHBOARD_DATA = __DASHBOARD_JSON__;
    const state = {
      activeIndustry: "",
      activeDepth: "",
      navRoot: "overview",
      marketCategory: "수급",
      futureCategory: "전체",
      futureView: "timeline",
      activeFutureId: "",
      trackRecordSort: "predicted",
      trackRecordSubject: "",
      companyArcChapters: {},
      companyArcCompanies: {},
      isReordering: false,
      draftIndustryOrder: null,
      draggedMenuItem: null,
      language: "ko",
      currency: "usd",
      countryFilter: "ALL",
      timeZone: "Asia/Seoul",
      favoriteMetricIds: new Set(),
      favoritePage: 0,
      briefingIndex: DASHBOARD_DATA.briefing_index || null,
      selectedBriefingId: "",
      selectedBriefingCard: null,
      briefingTimeMenuOpen: false,
      searchActive: false,
      searchQuery: "",
      searchResults: [],
      searchResultMeta: new Map(),
      searchSelectedIndex: -1,
      searchFuzzyMode: false,
      searchRestoreScrollY: 0,
      searchIndex: [],
      compareBaseMetricId: "",
      compareMetricIds: [],
      compareOpen: false,
      compareQuery: "",
      compareResults: [],
      compareMode: "raw",
      compareRange: "all",
      compareWarning: "",
      longHistoryData: null,
      gaugeHistoryData: null,
      gaugeHistoryOpen: {},
      gaugeHistoryRange: {},
      calendarSelectedDate: "",
      calendarViewMonth: "",
      calendarCategoryFilter: "all",
      calendarFilterDirection: "right",
      signalLog: { events: [] },
      signalFilter: "current",
      signalHistoryPage: 0,
      metricNotes: { version: 1, notes: {} },
      activeMetricDetailId: "",
      interpretationExpanded: {},
      detailMetadataExpanded: {},
      activeNoteMetricId: "",
      activeNoteEntryId: "",
      noteInitialText: "",
      applyingHashRoute: false
    };
    const favoriteMetricStorageKey = "dashboard-favorite-metrics";
    const recentSearchStorageKey = "dashboard-recent-searches";
    const recentMetricStorageKey = "dashboard-recent-metrics";
    const recentCompareStorageKey = "dashboard-recent-compares";
    const signalHistoryReadStorageKey = "dashboard-signal-history-read-at";
    const signalHistoryPageSize = 10;
    const metricNotesStorageKey = "dashboard-metric-notes";
    const noteMaxLength = 500;
    const mobileDrawerQuery = window.matchMedia ? window.matchMedia("(max-width: 760px)") : { matches: false };
    let scrollSpyFrame = 0;
    let suppressMenuClick = false;
    let searchDebounceTimer = 0;
    let compareDebounceTimer = 0;
    let gaugeHistoryPromise = null;
    const groupOrder = [
      "판매액(WSTS)", "판매액", "시장 매출", "가격/수요", "투자/장비", "수출",
      "판매/수요", "판매량", "배터리 원재료",
      "운임/해운", "선가/발주",
      "원자재 가격", "중국 경기",
      "에너지 가격", "원유/원료", "화학 스프레드", "스프레드/마진",
      "금리", "신용 스프레드", "스프레드", "금리/스프레드", "은행 건전성", "대출/건전성",
      "주택 경기", "건설 선행", "금융비용", "주택 시장",
      "시장지수", "환율", "리스크", "시장 분위기", "핵심 지표", "대표주가"
    ];
    const translations = {
      ko: {
        title: "산업별 지표 대시보드",
        settings: "설정",
        darkMode: "다크모드",
        currency: "통화",
        lightMode: "라이트",
        darkModeState: "다크",
        language: "언어변경",
        languageKorean: "한국어",
        languageEnglish: "English",
        timeZone: "시간대",
        timeZoneKorea: "한국 (KST, UTC+9)",
        timeZoneUs: "미국 동부 (ET, UTC-5/UTC-4)",
        timeZoneKoreaOption: "한국(KST)",
        timeZoneUsOption: "미국(ET)",
        timeZoneSwitchKorea: "한국으로 변경",
        timeZoneSwitchUs: "미국 동부로 변경",
        timeZoneCurrentKorea: "현재 한국 (KST, UTC+9)",
        timeZoneCurrentUs: "현재 미국 동부 (ET, UTC-5/UTC-4)",
        reorderMenu: "메뉴 순서변경",
        notesExport: "메모 백업",
        notesImport: "메모 복원",
        analyticsCollection: "방문 분석",
        analyticsEnabled: "켜짐",
        analyticsDisabled: "꺼짐",
        countrySelect: "국가 선택",
        privacyPolicy: "개인정보처리방침",
        termsOfService: "이용약관",
        footerCopyright: "© 2026 luceforge studio. All rights reserved.",
        footerDisclaimer: "본 서비스는 공개 데이터를 바탕으로 한 정보 제공용 참고 자료이며, 투자 자문·권유 또는 매매 추천이 아닙니다. 표시되는 데이터의 정확성, 완전성, 최신성은 보장되지 않으며 오류·누락·지연으로 발생한 손해에 대해 책임을 지지 않습니다. 모든 투자 판단과 그에 따른 손익의 책임은 이용자에게 있으며, 투자 원금 손실이 발생할 수 있습니다.",
        cancel: "취소",
        save: "저장",
        close: "닫기",
        edit: "수정",
        delete: "삭제",
        noteTitle: "메모",
        myNote: "내 메모",
        editNote: "메모 쓰기",
        downloadCsv: "CSV",
        noteHistory: "메모 이력",
        noteHistoryEmpty: "아직 기록한 메모가 없습니다.",
        noteUpdatedAt: "마지막 수정",
        noteNeverSaved: "아직 저장 전",
        notePlaceholder: "지표에 대해 기록해보세요",
        noteDiscardConfirm: "저장하지 않은 메모가 있습니다. 닫을까요?",
        noteSaveFailed: "메모를 저장하지 못했습니다. 브라우저 저장공간을 확인하세요.",
        notesImportFailed: "메모 파일을 읽지 못했습니다.",
        offlineData: "오프라인",
        offlineAsOf: "기준 데이터",
        empty: "표시할 지표가 없습니다.",
        metric: "지표",
        description: "설명",
        lastUpdated: "마지막 업데이트일",
        dataAsOf: "데이터 기준",
        lastChecked: "마지막 확인",
        nextUpdate: "다음 예정일",
        chart: "차트",
        metricSummary: "지표명",
        metricValueShort: "지표값",
        currentValue: "현재값",
        previousChange: "전기 변화",
        previousChangePct: "전기 변화율",
        detailReferenceMax: "최고",
        detailReferenceCurrent: "현재",
        detailReferenceMin: "최저",
        interpretationColumnSignal: "해석",
        interpretationColumnPosition: "위치",
        interpretationColumnMeaning: "의미 설명",
        marketDiagnosis: "시장 진단",
        marketThermometer: "시장 온도계",
        recessionSignals: "경기침체 시그널",
        fearGreedIndex: "공포탐욕지수",
        recessionRiskLow: "낮음",
        recessionRiskModerate: "보통",
        recessionRiskHigh: "높음",
        recessionStatusStable: "안정",
        recessionStatusWatch: "주의",
        recessionStatusDanger: "위험",
        thermometerBasis: "근거 지표",
        gaugeHistory: "추이",
        gaugeHistoryLoading: "추이를 불러오는 중입니다.",
        gaugeHistoryEmpty: "아직 쌓인 추이 데이터가 부족합니다.",
        gaugeHistory3m: "3M",
        gaugeHistory1y: "1Y",
        gaugeHistoryAll: "전체",
        percentile10y: "10년 백분위",
        fullRange: "전체 기간 범위",
        dataSince: "데이터 시작",
        rangeRecent: "최근",
        rangeFull: "전체 기간",
        lastUpdatedInline: "최근 업데이트 일시",
        percentileBandLegend: "과거 20~80% 구간(중앙값)",
        heatLabel: "열기",
        staleBadge: "갱신 지연",
        yoy: "YoY",
        visiblePeriod: "표시 기간",
        updateFrequency: "업데이트 주기",
        irregular: "비정기",
        menuLabel: "산업 메뉴",
        drawerTitle: "메뉴",
        openMenu: "메뉴 열기",
        closeMenu: "메뉴 닫기",
        scrollTop: "최상단 이동",
        toggleTheme: "다크모드 전환",
        showKrw: "원화 표시",
        showUsd: "달러 표시",
        currencyKrwName: "원화",
        currencyUsdName: "달러",
        themeLightName: "라이트",
        themeDarkName: "다크",
        tooltipPeriod: "연도",
        tooltipValue: "지표",
        tooltipChange: "증감",
        todayChanges: "오늘 변경",
        showDailyChanges: "오늘 변경된 내용 확인하기",
        morningBriefing: "AI 요약",
        aiBriefing: "AI 요약",
        fallbackBriefing: "룰 기반 요약",
        selectBriefingDate: "브리핑 날짜 선택",
        previousBriefing: "이전 브리핑",
        nextBriefing: "다음 브리핑",
        favoriteMetrics: "즐겨찾기",
        favoriteCount: "개",
        favoritePreviousPage: "이전 즐겨찾기",
        favoriteNextPage: "다음 즐겨찾기",
        addFavorite: "별표 추가",
        removeFavorite: "별표 해제",
        briefingDisclaimer: "AI는 틀릴 수 있어요. 원자료를 함께 확인하세요.",
        updatedCount: "업데이트",
        newCount: "신규",
        noDailyChanges: "오늘 변경된 지표 없음",
        dailyHeatmap: "오늘 움직인 지표",
        updatedBadge: "업데이트",
        newBadge: "New",
        fetchUpdated: "업데이트됨",
        fetchNoNewData: "신규 데이터 없음",
        fetchFailed: "수집 실패(이전 값 표시 중)",
        dataFreshness: "데이터 업데이트 현황",
        dataFreshnessCurrent: "정상",
        dataFreshnessUpdated: "새 값 반영",
        dataFreshnessWaiting: "발표 대기",
        dataFreshnessDelayed: "갱신 지연",
        dataFreshnessFailed: "수집 실패",
        dataFreshnessLastChecked: "마지막 확인",
        dataFreshnessLatestObservation: "최신 관측",
        dataFreshnessSources: "소스별 현황",
        metricDetailDrawerTitle: "지표 상세",
        metricDetailDrawerClose: "지표 상세 닫기",
        detailMetaMore: "자세히 보기",
        detailMetaLess: "접기",
        signalHistoryTitle: "주요 시그널 히스토리",
        signalHistoryClose: "시그널 이력 닫기",
        signalCurrent: "현재 발동중",
        signalHistory: "히스토리",
        signalAll: "전체",
        signalTriggeredOnly: "발동만",
        signalTriggered: "발동",
        signalCleared: "해제",
        signalBackfilled: "소급",
        signalCurrentEmpty: "발동 중인 시그널이 없습니다.",
        signalHistoryEmpty: "시그널 이력이 없습니다.",
        signalPreviousPage: "이전",
        signalNextPage: "다음",
        interpretationMore: "더보기",
        interpretationLess: "접기",
        marketNav: "시황",
        indicatorNav: "산업",
        futureNav: "미래",
        back: "뒤로",
        marketOverview: "홈",
        marketFlows: "수급",
        marketCredit: "신용·예탁금",
        marketRates: "금리·채권",
        marketLiquidity: "유동성",
        marketAssets: "원자재·크립토",
        marketSentiment: "심리·변동성",
        marketValuation: "밸류에이션",
        marketCalendar: "캘린더",
        scheduleAlerts: "일정/알림",
        calendarSnapshotTitle: "주요 일정",
        calendarSnapshotCopy: "미국 서비스업 경기와 주택 시장을 알 수 있는 지표 발표가 예정되어 있어요",
        recentAlerts: "최근 알림",
        noRecentAlerts: "최근 알림이 없습니다.",
        calendarDate: "날짜",
        calendarType: "구분",
        calendarCountry: "국가",
        calendarSchedule: "일정",
        calendarDday: "D-day",
        calendarPolicy: "통화정책",
        calendarMacro: "거시경제",
        calendarMarket: "시장일정",
        calendarCorporate: "기업",
        calendarIndustry: "산업",
        calendarTodayTomorrow: "오늘·내일",
        calendarThisWeek: "이번 주",
        calendarNext30: "향후 30일",
        calendarPast7: "지난 7일",
        calendarNoEvents: "표시할 일정이 없습니다.",
        previousMonth: "이전 달",
        nextMonth: "다음 달",
        calendarFed: "연준",
        calendarBok: "한은",
        calendarUsData: "미 지표",
        calendarExpiry: "만기",
        calendarHoliday: "휴장",
        calendarEarnings: "실적",
        calendarFuture: "미래",
        calendarEvent: "일정",
        metricSearch: "지표 검색",
        metricSearchPlaceholder: "지표명, 업종, 주체, 출처 검색",
        metricSearchCount: "검색 결과",
        similarResults: "유사 결과",
        metricSearchMore: "개는 아래 표에서 확인하세요",
        metricSearchEmpty: "에 해당하는 지표가 없습니다",
        compareAdd: "비교",
        compareDisplayBasis: "표시 기준",
        comparePeriod: "기간",
        compareSearchPlaceholder: "비교할 지표 검색 · 예) S&P500, 원/달러 환율",
        compareAddMetric: "지표 추가",
        compareRaw: "원 단위",
        compareIndexed: "=100 지수화",
        compareAllRange: "전체",
        compareRecent: "최근 비교",
        compareShortRange: "비교 가능 구간이 짧습니다",
        compareFlowBadge: "20일 누적",
        compareLimitCount: "최대 4개 지표까지 비교할 수 있습니다.",
        compareUnitLimit: "원단위 비교는 2개 지표까지만 가능합니다.",
        compareLimitRaw: "음수 값 지표는 2개까지만 원단위 비교",
        compareNeedsPositive: "표시 구간에 0 이하 값이 있어 =100 비교를 사용할 수 없습니다",
        futureTimelineTitle: "미래 타임라인",
        futureTimelineIntro: "예측, 현재 진척, 관련 기업을 한 흐름으로 묶어 봅니다.",
        futureAll: "전체",
        futureToday: "오늘",
        futureAchieved: "이미 달성된 예측",
        futurePrediction: "예측",
        futureProgress: "진척 지표",
        futureCompanies: "관련 기업",
        futureSource: "예측 출처",
        futureNoMetrics: "연결된 지표 없음",
        futureNoCompanies: "연결된 기업 없음",
        futureStatusAchieved: "달성",
        futureStatusUpcoming: "다가오는 예측",
        futureStatusDistant: "먼 예측",
        futureStatusWatch: "관찰",
        futureUnknownTrack: "시점을 매기지 않는 관찰 항목",
        futureNatureFrontier: "프런티어",
        futureNatureProduct: "제품",
        futureNatureGovernance: "거버넌스 · 관찰용",
        futureNatureScenario: "종합 시나리오",
        futureInvestableTrue: "직접 투자 가능",
        futureInvestablePartial: "간접 투자",
        futureInvestableFalse: "직접 투자 대상 아님",
        futureNoInvestableCompanies: "직접 투자할 상장사가 뚜렷하지 않은 분야입니다.",
        futurePartialInvesting: "상장사는 대부분 간접 노출이며 핵심 사업자는 비상장입니다.",
        futurePrivatePlayers: "비상장 핵심 주체",
        futureGovernanceIssues: "핵심 쟁점",
        futureForecastLow: "낮은 확신의 시나리오",
        futureManufacturerForecast: "제조사 목표",
        futureStale: "업데이트 점검 필요",
        futureRoadmapTitle: "기술 로드맵",
        futureRoadmapNotice: "미래 구간은 운영자의 추정입니다. 근거와 수정 이력을 함께 보세요.",
        futureRoadmapDone: "완료",
        futureRoadmapActive: "진행",
        futureRoadmapProjected: "추정",
        futureRoadmapGhost: "이전 추정",
        futureRoadmapToday: "오늘",
        futureRoadmapEarlier: "이전 연도 펼치기",
        futureRoadmapLater: "먼 미래 펼치기",
        futureRoadmapBasis: "기간 근거",
        futureRoadmapRevisions: "재추정 이력",
        futureRoadmapInitial: "최초 추정",
        futureRoadmapDelayed: "년 밀림",
        futureRoadmapAdvanced: "년 당김",
        futureRoadmapLadder: "연결된 사다리",
        futureBreakdownTitle: "무엇이 필요한가",
        futureBreakdownCurrent: "현재",
        futureBreakdownRequired: "필요",
        futureBreakdownGapMet: "필요 단계 도달",
        futureBreakdownGapSteps: "남은 간격",
        futureBreakdownStepSuffix: "단계",
        futureBreakdownBottleneck: "병목",
        futureBreakdownLowConfidence: "낮은 확신",
        futureBreakdownStale: "점검 필요",
        futureBreakdownAchievedBy: "도달",
        futureBreakdownPursuing: "추격",
        futureBreakdownMetric: "확인 지표",
        futureBreakdownSource: "근거",
        futureReadingsTitle: "더 깊이 알아보기",
        futureReadingsCommonTitle: "미래를 읽는 법",
        futureReadingBeginner: "입문",
        futureReadingIntermediate: "중급",
        futureReadingAdvanced: "심화",
        futureReadingTrusted: "신뢰 도메인",
        futureReadingAuto: "자동 수집",
        futureReadingSubscription: "구독",
        futureReadingOpen: "원문 열기",
        futureReadingNotice: "링크는 공개 자료 위주로 선별했으며, 내용은 투자 추천이 아니라 기술 흐름을 이해하기 위한 참고 자료입니다.",
        futureGlossaryLearnMore: "자세히",
        futureTrackRecordTitle: "과거 예측",
        futureTrackRecordIntro: "과거 기술 예측이 실제로 언제 왔는지 비교해보세요.",
        futureTrackRecordEntryCopy: "미래 예측을 더 차분하게 읽기 위한 과거 기록입니다.",
        futureTrackRecordBack: "타임라인",
        futureTrackRecordSort: "정렬",
        futureTrackRecordSortPredicted: "예측 연도순",
        futureTrackRecordSortError: "오차 큰 순",
        futureTrackRecordSortSubject: "주체별",
        futureTrackRecordAllSubjects: "전체 주체",
        futureTrackRecordStillOpen: "아직",
        futureTrackRecordNow: "현재",
        futureTrackRecordExact: "정확",
        futureTrackRecordEarly: "빠름",
        futureTrackRecordLate: "늦음",
        futureTrackYearSuffix: "년",
        futureTrackRecordWhat: "예측",
        futureTrackRecordOutcome: "결과",
        futureTrackRecordLesson: "교훈",
        futureTrackRecordActualBasis: "판정 기준",
        futureTrackRecordSource: "예측 출처",
        futureTrackRecordEmpty: "표시할 예측 기록이 없습니다.",
        futureTrackRecordJudgedSuffix: "건 판정",
        futureTrackRecordHitSuffix: "건 적중",
        futureTrackRecordPredictedPoint: "예측 시점",
        futureTrackRecordActualPoint: "실제 도래",
        futureCompanyArcsTitle: "기업의 흥망",
        futureCompanyArcsIntro: "기술이 성장해도 어떤 기업이 살아남는지는 별개의 문제였습니다.",
        futureCompanyArcNotice: "명목 시가총액을 미 달러로 비교합니다. 오래된 기업과 상장폐지 기업은 공시·거래가액을 바탕으로 한 근사값이 포함되므로 각 라인의 출처를 확인하세요.",
        futureCompanyArcCompanies: "개 기업",
        futureCompanyArcAsOf: "수록 기준",
        futureCompanyArcAll: "전체 보기",
        futureCompanyArcPrevious: "이전 시대",
        futureCompanyArcNext: "다음 시대",
        futureCompanyArcSource: "출처 확인",
        futureCompanyArcConfidence: "확신",
        futureCompanyArcExact: "공개 시가총액 이력",
        futureCompanyArcMarketCap: "시가총액",
        futureCompanyArcApprox: "사료 근사",
        futureCompanyArcOngoing: "현재 진행",
        futureCompanyArcBankrupt: "파산",
        futureCompanyArcAcquired: "피인수",
        futureCompanyArcDelisted: "상장폐지",
        futureCompanyArcIndex: "시가총액 · USD · 로그축",
        futureTrackStatusEarly: "빨리 옴",
        futureTrackStatusOnTime: "거의 정확",
        futureTrackStatusLate: "늦음",
        futureTrackStatusMissed: "미완",
        futureTrackStatusPending: "판정 대기",
        futureEmpty: "표시할 미래 기술이 없습니다."
      },
      en: {
        title: "Industry Metrics Dashboard",
        settings: "Settings",
        darkMode: "Dark mode",
        currency: "Currency",
        lightMode: "Light",
        darkModeState: "Dark",
        language: "Language",
        languageKorean: "Korean",
        languageEnglish: "English",
        timeZone: "Time zone",
        timeZoneKorea: "Korea (KST, UTC+9)",
        timeZoneUs: "US Eastern (ET, UTC-5/UTC-4)",
        timeZoneKoreaOption: "Korea(KST)",
        timeZoneUsOption: "US(ET)",
        timeZoneSwitchKorea: "Switch to KST",
        timeZoneSwitchUs: "Switch to ET",
        timeZoneCurrentKorea: "Current: Korea (KST, UTC+9)",
        timeZoneCurrentUs: "Current: US Eastern (ET, UTC-5/UTC-4)",
        reorderMenu: "Reorder menu",
        notesExport: "Back up notes",
        notesImport: "Restore notes",
        analyticsCollection: "Usage analytics",
        analyticsEnabled: "On",
        analyticsDisabled: "Off",
        countrySelect: "Country",
        privacyPolicy: "Privacy Policy",
        termsOfService: "Terms of Service",
        footerCopyright: "© 2026 luceforge studio. All rights reserved.",
        footerDisclaimer: "This service provides reference information based on public data and does not offer investment advice, solicitation, or trading recommendations. The accuracy, completeness, and timeliness of displayed data are not guaranteed, and we are not liable for losses arising from errors, omissions, or delays. All investment decisions and resulting gains or losses are the user's responsibility, and loss of principal is possible.",
        cancel: "Cancel",
        save: "Save",
        close: "Close",
        edit: "Edit",
        delete: "Delete",
        noteTitle: "Note",
        myNote: "My note",
        editNote: "Edit note",
        downloadCsv: "CSV",
        noteHistory: "Note history",
        noteHistoryEmpty: "No notes yet.",
        noteUpdatedAt: "Updated",
        noteNeverSaved: "Not saved yet",
        notePlaceholder: "Record notes about this metric.",
        noteDiscardConfirm: "You have unsaved note changes. Close anyway?",
        noteSaveFailed: "Could not save the note. Check browser storage.",
        notesImportFailed: "Could not read the notes file.",
        offlineData: "Offline",
        offlineAsOf: "data as of",
        empty: "No metrics to display.",
        metric: "Metric",
        description: "Description",
        lastUpdated: "Last updated",
        dataAsOf: "Data as of",
        lastChecked: "Last checked",
        nextUpdate: "Next update",
        chart: "Chart",
        metricSummary: "Metric",
        metricValueShort: "Value",
        currentValue: "Current",
        previousChange: "Previous change",
        previousChangePct: "Previous %",
        detailReferenceMax: "High",
        detailReferenceCurrent: "Current",
        detailReferenceMin: "Low",
        interpretationColumnSignal: "Signal",
        interpretationColumnPosition: "Position",
        interpretationColumnMeaning: "Meaning",
        marketDiagnosis: "Market Diagnosis",
        yoy: "YoY",
        visiblePeriod: "Period",
        updateFrequency: "Frequency",
        irregular: "Irregular",
        menuLabel: "Industry menu",
        drawerTitle: "Menu",
        openMenu: "Open menu",
        closeMenu: "Close menu",
        scrollTop: "Back to top",
        toggleTheme: "Toggle dark mode",
        showKrw: "Show KRW",
        showUsd: "Show USD",
        currencyKrwName: "KRW",
        currencyUsdName: "USD",
        themeLightName: "Light",
        themeDarkName: "Dark",
        tooltipPeriod: "Period",
        tooltipValue: "Value",
        tooltipChange: "Change",
        marketThermometer: "Market Thermometer",
        recessionSignals: "Recession Signals",
        fearGreedIndex: "Fear & Greed",
        recessionRiskLow: "Low",
        recessionRiskModerate: "Moderate",
        recessionRiskHigh: "High",
        recessionStatusStable: "Stable",
        recessionStatusWatch: "Watch",
        recessionStatusDanger: "Risk",
        thermometerBasis: "Basis indicators",
        gaugeHistory: "Trend",
        gaugeHistoryLoading: "Loading trend history.",
        gaugeHistoryEmpty: "Not enough history yet.",
        gaugeHistory3m: "3M",
        gaugeHistory1y: "1Y",
        gaugeHistoryAll: "All",
        percentile10y: "10y percentile",
        fullRange: "All-time range",
        dataSince: "Data since",
        rangeRecent: "Recent",
        rangeFull: "Full history",
        lastUpdatedInline: "Last updated",
        percentileBandLegend: "Historical 20-80% range (median)",
        heatLabel: "heat",
        staleBadge: "Stale",
        todayChanges: "Today",
        showDailyChanges: "View today's changes",
        morningBriefing: "AI Summary",
        aiBriefing: "AI summary",
        fallbackBriefing: "Rule summary",
        selectBriefingDate: "Select briefing date",
        previousBriefing: "Previous briefing",
        nextBriefing: "Next briefing",
        favoriteMetrics: "Starred Metrics",
        favoriteCount: "items",
        favoritePreviousPage: "Previous favorites",
        favoriteNextPage: "Next favorites",
        addFavorite: "Add star",
        removeFavorite: "Remove star",
        briefingDisclaimer: "AI can be wrong. Check the original sources too.",
        updatedCount: "Updated",
        newCount: "New",
        noDailyChanges: "No changed metrics today",
        dailyHeatmap: "Today's movers",
        updatedBadge: "Updated",
        newBadge: "New",
        fetchUpdated: "Updated",
        fetchNoNewData: "No new data",
        fetchFailed: "Fetch failed; showing prior value",
        dataFreshness: "Data update status",
        dataFreshnessCurrent: "Current",
        dataFreshnessUpdated: "New values",
        dataFreshnessWaiting: "Awaiting release",
        dataFreshnessDelayed: "Delayed",
        dataFreshnessFailed: "Failed",
        dataFreshnessLastChecked: "Last checked",
        dataFreshnessLatestObservation: "Latest observation",
        dataFreshnessSources: "Status by source",
        metricDetailDrawerTitle: "Metric Detail",
        metricDetailDrawerClose: "Close metric detail",
        detailMetaMore: "View details",
        detailMetaLess: "Show less",
        signalHistoryTitle: "Key Signal History",
        signalHistoryClose: "Close signal history",
        signalCurrent: "Active now",
        signalHistory: "History",
        signalAll: "All",
        signalTriggeredOnly: "Triggered",
        signalTriggered: "Triggered",
        signalCleared: "Cleared",
        signalBackfilled: "Backfilled",
        signalCurrentEmpty: "No signals are active.",
        signalHistoryEmpty: "No signal history.",
        signalPreviousPage: "Previous",
        signalNextPage: "Next",
        interpretationMore: "Show more",
        interpretationLess: "Show less",
        marketNav: "Market",
        indicatorNav: "Industries",
        futureNav: "Future",
        back: "Back",
        marketOverview: "Home",
        marketFlows: "Flows",
        marketCredit: "Credit/Cash",
        marketRates: "Rates/Bonds",
        marketLiquidity: "Liquidity",
        marketAssets: "Commodities/Crypto",
        marketSentiment: "Sentiment/Volatility",
        marketValuation: "Valuation",
        marketCalendar: "Calendar",
        scheduleAlerts: "Schedule/Alerts",
        calendarSnapshotTitle: "Key events",
        calendarSnapshotCopy: "Upcoming releases can give clues on services activity and the housing market.",
        recentAlerts: "Recent alerts",
        noRecentAlerts: "No recent alerts.",
        calendarDate: "Date",
        calendarType: "Type",
        calendarCountry: "Country",
        calendarSchedule: "Event",
        calendarDday: "D-day",
        calendarPolicy: "Policy",
        calendarMacro: "Macro",
        calendarMarket: "Market",
        calendarCorporate: "Corporate",
        calendarIndustry: "Industry",
        calendarTodayTomorrow: "Today/Tomorrow",
        calendarThisWeek: "This week",
        calendarNext30: "Next 30 days",
        calendarPast7: "Past 7 days",
        calendarNoEvents: "No events to show.",
        previousMonth: "Previous month",
        nextMonth: "Next month",
        calendarFed: "Fed",
        calendarBok: "BOK",
        calendarUsData: "US data",
        calendarExpiry: "Expiry",
        calendarHoliday: "Holiday",
        calendarEarnings: "Earnings",
        calendarFuture: "Future",
        calendarEvent: "Event",
        metricSearch: "Search metrics",
        metricSearchPlaceholder: "Search metric, sector, investor, source",
        metricSearchCount: "Results",
        similarResults: "Similar results",
        metricSearchMore: "more in the tables below",
        metricSearchEmpty: "has no matching metrics",
        compareAdd: "Compare",
        compareDisplayBasis: "Display",
        comparePeriod: "Period",
        compareSearchPlaceholder: "Search metric to compare · e.g. S&P 500, USD/KRW",
        compareAddMetric: "Add metric",
        compareRaw: "Raw",
        compareIndexed: "Index =100",
        compareAllRange: "All",
        compareRecent: "Recent",
        compareShortRange: "Comparable window is short",
        compareFlowBadge: "20d sum",
        compareLimitCount: "Up to 4 metrics can be compared.",
        compareUnitLimit: "Raw-unit comparison is limited to two metrics.",
        compareLimitRaw: "Negative-value metrics are limited to two raw series",
        compareNeedsPositive: "=100 is unavailable because the visible range includes zero or negative values",
        futureTimelineTitle: "Future Timeline",
        futureTimelineIntro: "Track predictions, current progress, and the companies linked to each theme.",
        futureAll: "All",
        futureToday: "Today",
        futureAchieved: "Achieved predictions",
        futurePrediction: "Prediction",
        futureProgress: "Progress metrics",
        futureCompanies: "Related companies",
        futureSource: "Prediction source",
        futureNoMetrics: "No linked metrics",
        futureNoCompanies: "No linked companies",
        futureStatusAchieved: "Achieved",
        futureStatusUpcoming: "Upcoming",
        futureStatusDistant: "Distant",
        futureStatusWatch: "Watch",
        futureUnknownTrack: "Observation items without a target year",
        futureNatureFrontier: "Frontier",
        futureNatureProduct: "Product",
        futureNatureGovernance: "Governance · observation",
        futureNatureScenario: "Scenario",
        futureInvestableTrue: "Directly investable",
        futureInvestablePartial: "Indirect exposure",
        futureInvestableFalse: "Not an investment theme",
        futureNoInvestableCompanies: "There is no clear publicly listed pure-play investment in this field.",
        futurePartialInvesting: "Listed names are mostly indirect exposure; key operators are private.",
        futurePrivatePlayers: "Key private players",
        futureGovernanceIssues: "Key issues",
        futureForecastLow: "Low-confidence scenario",
        futureManufacturerForecast: "Manufacturer target",
        futureStale: "Update due",
        futureRoadmapTitle: "Technology roadmap",
        futureRoadmapNotice: "Future periods are editorial estimates. Review the basis and revision history together.",
        futureRoadmapDone: "Done",
        futureRoadmapActive: "Active",
        futureRoadmapProjected: "Estimated",
        futureRoadmapGhost: "Prior estimate",
        futureRoadmapToday: "Today",
        futureRoadmapEarlier: "Show earlier years",
        futureRoadmapLater: "Show later years",
        futureRoadmapBasis: "Basis",
        futureRoadmapRevisions: "Revision history",
        futureRoadmapInitial: "Initial estimate",
        futureRoadmapDelayed: "y delayed",
        futureRoadmapAdvanced: "y earlier",
        futureRoadmapLadder: "Linked ladder",
        futureBreakdownTitle: "What Must Happen",
        futureBreakdownCurrent: "Current",
        futureBreakdownRequired: "Required",
        futureBreakdownGapMet: "Required level reached",
        futureBreakdownGapSteps: "Remaining gap",
        futureBreakdownStepSuffix: "steps",
        futureBreakdownBottleneck: "Bottleneck",
        futureBreakdownLowConfidence: "Low confidence",
        futureBreakdownStale: "Needs review",
        futureBreakdownAchievedBy: "Achieved by",
        futureBreakdownPursuing: "Pursuing",
        futureBreakdownMetric: "Metric",
        futureBreakdownSource: "Basis",
        futureReadingsTitle: "Read Deeper",
        futureReadingsCommonTitle: "How to Read the Future",
        futureReadingBeginner: "Beginner",
        futureReadingIntermediate: "Intermediate",
        futureReadingAdvanced: "Advanced",
        futureReadingTrusted: "Trusted domain",
        futureReadingAuto: "Auto-collected",
        futureReadingSubscription: "Subscription",
        futureReadingOpen: "Open source",
        futureReadingNotice: "These links are curated public materials for understanding technology trends, not investment recommendations.",
        futureGlossaryLearnMore: "Learn more",
        futureTrackRecordTitle: "Past Predictions",
        futureTrackRecordIntro: "Compare when past technology forecasts actually arrived.",
        futureTrackRecordEntryCopy: "A calibration record for reading future predictions more calmly.",
        futureTrackRecordBack: "Timeline",
        futureTrackRecordSort: "Sort",
        futureTrackRecordSortPredicted: "Predicted year",
        futureTrackRecordSortError: "Largest error",
        futureTrackRecordSortSubject: "Forecaster",
        futureTrackRecordAllSubjects: "All forecasters",
        futureTrackRecordStillOpen: "Still open",
        futureTrackRecordNow: "Now",
        futureTrackRecordExact: "Exact",
        futureTrackRecordEarly: "early",
        futureTrackRecordLate: "late",
        futureTrackYearSuffix: "y",
        futureTrackRecordWhat: "Prediction",
        futureTrackRecordOutcome: "Outcome",
        futureTrackRecordLesson: "Lesson",
        futureTrackRecordActualBasis: "Judgment basis",
        futureTrackRecordSource: "Prediction source",
        futureTrackRecordEmpty: "No prediction records to show.",
        futureTrackRecordJudgedSuffix: " judged",
        futureTrackRecordHitSuffix: " hits",
        futureTrackRecordPredictedPoint: "Forecast date",
        futureTrackRecordActualPoint: "Actual arrival",
        futureCompanyArcsTitle: "Company Rise and Fall",
        futureCompanyArcsIntro: "A technology can thrive even when its early corporate leaders do not survive.",
        futureCompanyArcNotice: "The chart compares nominal market capitalizations in US dollars. Older and delisted-company values may be estimates based on filings or transaction values; check each line's source.",
        futureCompanyArcCompanies: "companies",
        futureCompanyArcAsOf: "As of",
        futureCompanyArcAll: "Full history",
        futureCompanyArcPrevious: "Previous era",
        futureCompanyArcNext: "Next era",
        futureCompanyArcSource: "View source",
        futureCompanyArcConfidence: "Confidence",
        futureCompanyArcExact: "Published market-cap history",
        futureCompanyArcMarketCap: "Market cap",
        futureCompanyArcApprox: "Historical approximation",
        futureCompanyArcOngoing: "Ongoing",
        futureCompanyArcBankrupt: "Bankrupt",
        futureCompanyArcAcquired: "Acquired",
        futureCompanyArcDelisted: "Delisted",
        futureCompanyArcIndex: "Market cap · USD · log scale",
        futureTrackStatusEarly: "Early",
        futureTrackStatusOnTime: "On time",
        futureTrackStatusLate: "Late",
        futureTrackStatusMissed: "Missed",
        futureTrackStatusPending: "Pending",
        futureEmpty: "No future technologies to show."
      }
    };

    function t(key) {
      return translations[state.language]?.[key] || translations.ko[key] || key;
    }

    const timeZoneOptions = {
      korea: "Asia/Seoul",
      us: "America/New_York"
    };
    const marketCategories = [
      { key: "수급", labelKey: "marketFlows" },
      { key: "신용·예탁금", labelKey: "marketCredit" },
      { key: "금리·채권", labelKey: "marketRates" },
      { key: "유동성", labelKey: "marketLiquidity" },
      { key: "원자재·크립토", labelKey: "marketAssets" },
      { key: "심리·변동성", labelKey: "marketSentiment" },
      { key: "밸류에이션", labelKey: "marketValuation" },
      { key: "캘린더", labelKey: "marketCalendar" }
    ];
    const overviewCategoryKey = "종합";
    const defaultMarketCategory = marketCategories[0]?.key || "수급";
    const futureAllCategory = "전체";
    const defaultFutureCategories = ["전체", "AI", "로봇·모빌리티", "바이오", "에너지", "우주"];
    const futureRoadmapRanges = {};
    const navStateStorageKey = "dashboard-nav-state";
    const englishIndustryFallbacks = {
      "반도체": "Semiconductors",
      "데이터인프라": "Data Infrastructure",
      "자동차": "Automobiles",
      "전기차": "EVs",
      "조선": "Shipbuilding",
      "철강/소재": "Steel & Materials",
      "화학/정유": "Chemicals & Refining",
      "은행/금융": "Banks & Financials",
      "건설/부동산": "Construction & Real Estate",
      "방산": "Defense",
      "스테이블코인": "Stablecoins",
      "전력": "Power",
      "로봇": "Robotics",
      "우주": "Space",
      "바이오": "Biotech",
      "배터리": "Batteries",
      "매크로": "Macro"
    };
    const englishGroupFallbacks = {
      "판매액": "Sales",
      "판매액(WSTS)": "Sales (WSTS)",
      "시장 매출": "Market Revenue",
      "가격/수요": "Price/Demand",
      "투자/장비": "Investment/Equipment",
      "수출": "Exports",
      "판매/수요": "Sales/Demand",
      "판매량": "Sales Volume",
      "판매": "Sales",
      "배터리 원재료": "Battery Raw Materials",
      "운임/해운": "Shipping Rates",
      "운임": "Shipping Rates",
      "선가/발주": "Newbuild Prices/Orders",
      "원자재 가격": "Commodity Prices",
      "원자재": "Commodities",
      "중국 경기": "China Macro",
      "에너지 가격": "Energy Prices",
      "에너지": "Energy",
      "원유/원료": "Crude/Feedstock",
      "화학 스프레드": "Chemical Spreads",
      "스프레드/마진": "Spreads/Margins",
      "금리": "Rates",
      "신용 스프레드": "Credit Spreads",
      "스프레드": "Spreads",
      "금리/스프레드": "Rates/Spreads",
      "은행 건전성": "Bank Asset Quality",
      "대출/건전성": "Lending/Asset Quality",
      "주택 경기": "Housing Activity",
      "건설 선행": "Construction Leads",
      "금융비용": "Financing Costs",
      "주택 시장": "Housing Market",
      "주택": "Housing",
      "시장지수": "Market Indexes",
      "환율": "FX",
      "리스크": "Risk",
      "시장 분위기": "Market Mood",
      "시장 심리": "Market Sentiment",
      "핵심 지표": "Core Metrics",
      "대표주가": "Representative Stock Prices",
      "대표주가/시장지수": "Representative Stocks/Market Indexes",
      "경기침체": "Recession",
      "물가": "Inflation",
      "외국인": "Foreign Investors",
      "개인": "Retail Investors",
      "예탁금": "Cash Deposits",
      "신용": "Margin Credit",
      "크립토": "Crypto",
      "변동성": "Volatility",
      "공포탐욕": "Fear & Greed",
      "밸류에이션": "Valuation",
      "수주": "Orders",
      "유동성": "Liquidity",
      "전력": "Power",
      "활동성": "Activity",
      "파이프라인": "Pipeline",
      "CAPEX": "CAPEX",
      "미국 유동성": "US Liquidity",
      "한국 유동성": "Korea Liquidity",
      "일본 유동성": "Japan Liquidity",
      "유럽 유동성": "Europe Liquidity",
      "국제 유동성": "Global Liquidity"
    };
    const englishDepthFallbacks = {
      "전체 업황": "Overall Cycle",
      "메모리 반도체": "Memory Semiconductors",
      "AI/GPU": "AI/GPU",
      "CPU/프로세서": "CPU/Processors",
      "파운드리": "Foundry",
      "장비": "Equipment",
      "패키징/후공정": "Packaging/Back-end",
      "소자/부품": "Devices/Components"
    };
    const englishFrequencyFallbacks = {
      "일간": "Daily",
      "주간": "Weekly",
      "월간": "Monthly",
      "분기": "Quarterly",
      "연간": "Annual",
      "비정기": "Irregular",
      "월간/비정기": "Monthly/Irregular",
      "연간/비정기": "Annual/Irregular"
    };
    const englishUnitFallbacks = {
      "$": "USD",
      "$B": "$B",
      "%": "%",
      "%p": "%p",
      "원": "KRW",
      "억원": "KRW 100mn",
      "조원": "tn KRW",
      "€B": "€B",
      "¥T": "¥T",
      "점": "pts",
      "배": "x",
      "건": "events",
      "K건": "k",
      "M대": "M units",
      "백만대": "M units",
      "백만달러": "USD mn",
      "TWh": "TWh",
      "NT$B": "NT$B"
    };
    const englishMetricNameFallbacks = {
      "삼성전자(005930.KS)": "Samsung Electronics (005930.KS)",
      "SK하이닉스(000660.KS)": "SK hynix (000660.KS)",
      "TSMC 월매출": "TSMC Monthly Revenue",
      "미국 자동차 판매": "US Auto Sales",
      "글로벌 EV 판매": "Global EV Sales",
      "BDI": "BDI",
      "철광석": "Iron Ore",
      "구리": "Copper",
      "알루미늄": "Aluminum",
      "WTI 유가": "WTI Crude Oil Price",
      "미국 기준금리": "US Policy Rate",
      "장단기 금리차": "Yield Curve Spread",
      "미국 주택착공": "US Housing Starts",
      "미국 방산 제조 계약": "US Defense Manufacturing Contracts",
      "USDT/USDC 총 발행량": "USDT/USDC Total Supply",
      "미국 전력수요": "US Power Demand",
      "글로벌 발사 건수": "Global Launch Count",
      "Phase 3 임상 시작": "Phase 3 Trial Starts",
      "리튬 가격": "Lithium Price",
      "코스피": "KOSPI",
      "코스닥": "KOSDAQ",
      "S&P 500": "S&P 500",
      "나스닥": "NASDAQ Composite",
      "다우": "Dow Jones Industrial Average",
      "Sahm Rule 침체 지표": "Sahm Rule Recession Indicator",
      "GDPNow 성장률": "GDPNow Growth Rate",
      "미국 CPI": "US CPI",
      "코스피 외국인 순매수": "KOSPI Foreign Net Buying",
      "코스피 외국인 매수": "KOSPI Foreign Buying",
      "코스피 외국인 매도": "KOSPI Foreign Selling",
      "코스닥 개인 순매수": "KOSDAQ Retail Net Buying",
      "고객예탁금": "Investor Cash Deposits",
      "한국 투자자예탁금": "Korea Investor Cash Deposits",
      "신용융자 잔고": "Margin Loan Balance",
      "한국 신용융자 잔고": "Korea Margin Loan Balance",
      "한국 CMA 잔고": "Korea CMA Balance",
      "미국 10년 국채금리": "US 10Y Treasury Yield",
      "한국 기준금리": "Korea Policy Rate",
      "미국 10Y-3M 금리차": "US 10Y-3M Treasury Spread",
      "미국 하이일드 회사채 OAS": "US High Yield Corporate OAS",
      "원/달러 환율": "USD/KRW Exchange Rate",
      "비트코인": "Bitcoin",
      "VIX": "VIX",
      "VKOSPI": "VKOSPI",
      "미국 CNN 공포탐욕지수": "US CNN Fear & Greed Index",
      "코스피 공포탐욕지수": "KOSPI Fear & Greed Index",
      "코스닥 공포탐욕지수": "KOSDAQ Fear & Greed Index",
      "코스피 PBR": "KOSPI PBR",
      "S&P 500 Shiller CAPE": "S&P 500 Shiller CAPE",
      "미국 하이일드 스프레드": "US High Yield Spread",
      "하이일드 스프레드": "High Yield Spread",
      "Sahm Rule": "Sahm Rule",
      "미국 CNN": "US CNN",
      "한국은행 총자산": "Bank of Korea Total Assets",
      "한국 본원통화": "Korea Monetary Base",
      "한국 M2": "Korea M2",
      "한국 Lf": "Korea Lf",
      "한국 L": "Korea L",
      "일본 BOJ 총자산": "BOJ Total Assets",
      "일본 본원통화": "Japan Monetary Base",
      "일본 M2": "Japan M2",
      "일본 BOJ 당좌예금": "BOJ Current Account Balances",
      "유럽 초과유동성": "Europe Excess Liquidity",
      "유럽 유로시스템 총자산": "Eurosystem Total Assets",
      "유럽 M3": "Europe M3",
      "유럽 본원통화": "Europe Base Money"
    };
    const englishMeaningFallbacks = {
      "전 세계 반도체 판매액입니다. 메모리와 비메모리를 모두 합친 시장 전체의 매출 흐름이라, 반도체 업황이 커지는지 줄어드는지 볼 때 기준으로 씁니다.": "Worldwide semiconductor sales show total global semiconductor revenue across memory and non-memory. They are the baseline for whether the semiconductor cycle is expanding or slowing.",
      "아시아·태평양 지역 반도체 판매액입니다. 한국, 대만, 중국, 일본 등 주요 생산·소비 거점의 수요 흐름을 보는 데 유용합니다.": "Asia Pacific semiconductor sales show demand across major production and consumption hubs such as Korea, Taiwan, China, and Japan.",
      "미주 지역 반도체 판매액입니다. 미국을 중심으로 데이터센터, 클라우드, 기업 IT 투자 수요가 반도체 매출에 얼마나 이어지는지 볼 때 참고합니다.": "Americas semiconductor sales show demand led by the US and help check how data center, cloud, and enterprise IT investment feed into chip revenue.",
      "AI 데이터센터와 클라우드 서버 투자가 얼마나 강한지 보여줍니다.": "Shows how strong AI data center and cloud server investment is.",
      "AWS와 물류·서버 투자의 강도를 함께 볼 수 있는 지표입니다.": "Shows the intensity of AWS, logistics, and server investment.",
      "구글 클라우드와 AI 인프라 투자 흐름을 확인합니다.": "Tracks Google Cloud and AI infrastructure investment.",
      "AI 추천·광고 시스템과 데이터센터 투자 강도를 보여줍니다.": "Shows data center investment intensity for AI recommendation and advertising systems.",
      "완성차 수요와 소비 경기 흐름을 확인하는 판매 지표입니다.": "Sales indicator for auto demand and consumer-cycle conditions.",
      "철강 원가와 중국 투자 수요를 반영하는 핵심 원재료입니다.": "Core raw material reflecting steel costs and Chinese investment demand.",
      "전기화와 제조업 경기를 민감하게 반영하는 경기 민감 금속입니다.": "Cyclical metal sensitive to electrification and manufacturing activity.",
      "경량 소재와 제조업 수요, 전력비 영향을 함께 받는 소재 가격입니다.": "Material price affected by lightweighting demand, manufacturing demand, and power costs.",
      "정유, 화학 원가와 인플레이션 압력을 동시에 움직이는 원재료 가격입니다.": "Feedstock price that affects refining, chemical costs, and inflation pressure.",
      "중앙은행이 정하는 정책금리입니다. 예금·대출금리, 기업 조달비용, 주식시장 할인율에 영향을 주는 기본 금리입니다.": "Policy rate set by the central bank. It affects deposit and lending rates, corporate funding costs, and equity discount rates.",
      "경기 기대와 은행 순이자마진 방향을 함께 보여주는 지표입니다.": "Shows both growth expectations and the direction of bank net interest margins.",
      "건설 경기의 실제 착공 모멘텀과 주택 공급 흐름을 보여줍니다.": "Shows actual construction momentum and the housing supply pipeline.",
      "방산 발주와 생산 사이클을 통해 방산 업체 수요가 강해지는지 확인합니다.": "Tracks whether defense-company demand is strengthening through orders and production cycles.",
      "달러 연동 스테이블코인의 유통량 변화로 온체인 달러 유동성과 결제/거래 수요를 확인합니다.": "Tracks USD-pegged stablecoin supply to read on-chain dollar liquidity and payment/trading demand.",
      "전력 생산과 가격 흐름으로 전력 인프라와 전력 수요 사이클을 확인합니다.": "Tracks power production and prices to read power infrastructure and demand cycles.",
      "한국 대형주 중심의 대표 주가지수입니다. 국내 증시 전체 방향과 외국인 자금 흐름을 볼 때 기준점으로 씁니다.": "Representative Korean large-cap equity index used as a baseline for domestic market direction and foreign investor flows.",
      "한국 성장주와 중소형주 비중이 큰 주가지수입니다. 개인투자자 심리와 성장주 위험 선호를 확인할 때 봅니다.": "Korean growth and small/mid-cap index used to read retail sentiment and growth-stock risk appetite.",
      "미국 대형주 500개로 구성된 대표 지수입니다. 글로벌 위험 선호와 미국 증시의 넓은 방향을 보는 기준입니다.": "Representative index of 500 large US companies, used to read global risk appetite and broad US market direction.",
      "기술주 비중이 높은 미국 주가지수입니다. AI, 반도체, 소프트웨어 같은 성장주 투자심리를 확인할 때 봅니다.": "US equity index with a heavy technology weight, useful for reading AI, semiconductor, and software growth-stock sentiment.",
      "미국 우량 대형주 중심의 주가지수입니다. 경기민감 대형주의 흐름과 미국 증시의 전통 산업 쪽 분위기를 볼 때 참고합니다.": "US blue-chip large-cap index used to read cyclicals and traditional-industry sentiment.",
      "실업률이 최근 저점보다 얼마나 높아졌는지 보는 경기침체 신호입니다. 0.5%p를 넘으면 과거에는 침체 진입 가능성이 커진 경우가 많았습니다.": "Recession signal measuring how far unemployment has risen from its recent low. Readings above 0.5pp have often coincided with elevated recession risk.",
      "애틀랜타 연은이 실시간 경제지표를 반영해 추정하는 미국 GDP 성장률 전망입니다. 경기 기대가 좋아지는지 식는지 빠르게 볼 때 씁니다.": "Atlanta Fed real-time estimate of US GDP growth, useful for quickly reading whether growth expectations are improving or cooling.",
      "미국 소비자물가 상승률입니다. 인플레이션 압력과 연준 금리 기대를 움직여 주식, 채권, 환율에 모두 영향을 줍니다.": "US consumer inflation. It moves inflation pressure and Fed rate expectations, affecting equities, bonds, and FX.",
      "증권계좌에 대기 중인 현금입니다. 늘어나면 주식시장으로 들어올 수 있는 대기 자금이 많아졌다는 뜻으로 봅니다.": "Cash waiting in securities accounts. When it rises, there is more potential cash that could move into the stock market.",
      "투자자가 빚을 내서 주식을 산 잔고입니다. 빠르게 늘면 과열 신호가 될 수 있고, 급감하면 반대매매 압력을 의심할 수 있습니다.": "Outstanding margin loans used by investors to buy stocks. A rapid rise can signal overheating, while a sharp drop can point to forced-selling pressure.",
      "CMA 계좌에 머무는 단기 대기자금입니다. 증시 주변의 현금 여력과 단기자금 선호가 커지는지 확인할 때 봅니다.": "Short-term cash parked in CMA accounts. It helps read cash availability around the equity market and demand for short-term cash products.",
      "수출주 원화 환산 매출과 외국인 수급에 영향을 주는 매크로 변수입니다.": "Macro variable affecting exporters' KRW-translated revenue and foreign investor flows.",
      "대표적인 위험자산이자 크립토 유동성 지표입니다. 글로벌 유동성, 위험 선호, 크립토 시장 분위기를 빠르게 확인할 때 봅니다.": "Major risk asset and crypto liquidity gauge used to read global liquidity, risk appetite, and crypto sentiment.",
      "시장 위험 회피 심리와 변동성 확대 여부를 봅니다.": "Tracks risk-off sentiment and volatility expansion.",
      "신용 위험과 자금 조달 여건이 얼마나 빡빡한지 확인합니다.": "Measures credit risk and how tight funding conditions are.",
      "주가를 장부가치와 비교한 밸류에이션 지표입니다. 낮을수록 시장이 자산가치 대비 싸게 거래되는지 볼 때 참고합니다.": "Valuation measure comparing price to book value; lower readings can indicate a cheaper market versus asset value.",
      "경기순환을 감안한 장기 이익 대비 주가 수준입니다. 미국 증시가 장기 평균보다 비싼지 싼지 판단할 때 봅니다.": "Cyclically adjusted valuation measure used to judge whether US equities are expensive or cheap versus long-term earnings.",
      "전기차 흐름을 이해할 때 참고하는 보조 지표입니다.": "Proxy indicator used to monitor EV trends.",
      "조선 흐름을 이해할 때 참고하는 보조 지표입니다.": "Proxy indicator used to monitor shipbuilding trends.",
      "반도체 흐름을 이해할 때 참고하는 보조 지표입니다.": "Proxy indicator used to monitor semiconductor trends.",
      "로봇 흐름을 이해할 때 참고하는 보조 지표입니다.": "Proxy indicator used to monitor robotics trends.",
      "우주 흐름을 이해할 때 참고하는 보조 지표입니다.": "Proxy indicator used to monitor space-industry trends.",
      "바이오 흐름을 이해할 때 참고하는 보조 지표입니다.": "Proxy indicator used to monitor biotech trends.",
      "배터리 흐름을 이해할 때 참고하는 보조 지표입니다.": "Proxy indicator used to monitor battery trends."
    };
    const englishTextFallbacks = {
      "계산 기반 해석": "Computed interpretation",
      "최근 10년 백분위": "10-year percentile",
      "중립": "Neutral",
      "탐욕": "Greed",
      "공포": "Fear",
      "낮음": "Low",
      "보통": "Moderate",
      "높음": "High",
      "안정": "Stable",
      "주의": "Watch",
      "위험": "Risk",
      "아침": "Morning",
      "장중": "Intraday",
      "마감": "Close",
      "아침 더미 브리핑": "Morning dummy briefing",
      "장중 더미 브리핑": "Intraday dummy briefing",
      "마감 더미 브리핑": "Close dummy briefing",
      "룰 기반 요약": "Rule summary",
      "급변 지표": "Top mover",
      "좋아진 흐름": "Improving trend",
      "주의할 흐름": "Watch list",
      "미국 CPI 발표": "US CPI release",
      "FOMC 결정": "FOMC decision",
      "한국은행 금통위": "BOK rate decision",
      "한국 옵션만기": "Korea options expiry",
      "NYSE 휴장": "NYSE holiday",
      "미국 PCE 발표": "US PCE release",
      "인플레이션 방향 확인": "Check inflation direction",
      "금리와 유동성 기대가 크게 움직일 수 있는 날": "Rates and liquidity expectations may move sharply",
      "국내 금리 민감 업종을 볼 때 중요": "Important for Korea rate-sensitive sectors",
      "수급 변동성이 커질 수 있는 날": "Market flows may become more volatile",
      "미국 주식시장 휴장": "US stock market holiday",
      "연준이 선호하는 물가 지표": "Inflation gauge preferred by the Fed",
      "공포 구간 더미 시그널입니다.": "Dummy fear-zone signal triggered.",
      "공포 구간 더미 시그널이 해제됐습니다.": "Dummy fear-zone signal cleared.",
      "침체 가능성 더미 시그널입니다.": "Dummy recession-risk signal triggered.",
      "밸류에이션과 심리가 역사적 평균 부근입니다. 계획된 적립식 투자를 유지하기 좋은 구간입니다.": "Valuation and sentiment are near historical averages. This is a reasonable zone to maintain planned periodic investing.",
      "침체 신호가 하나 켜져 있습니다. 다른 지표의 추세 전환 여부를 함께 확인하세요.": "One recession signal is active. Check whether other indicators are also turning.",
      "0에 가까울수록 공포, 100에 가까울수록 탐욕이 강한 구간입니다.": "Closer to 0 means fear; closer to 100 means greed.",
      "수익률곡선이 평탄합니다. 역전 여부를 지켜볼 구간입니다.": "The yield curve is flat. Watch whether it inverts.",
      "Sahm Rule 기준(0.50)을 넘었습니다. 침체가 이미 시작됐을 가능성이 있습니다.": "The Sahm Rule is above 0.50, which can indicate a recession may already have started.",
      "신용 스프레드가 확대되고 있습니다. 기업 부도위험 경계 구간입니다.": "Credit spreads are widening. This is a corporate default-risk watch zone.",
      "미국 성장률 추정치가 1% 아래로 둔화됐습니다.": "The US growth estimate has slowed below 1%.",
      "바이오 Phase 3 임상 시작 변화가 눈에 띕니다.": "Biotech Phase 3 trial starts stand out."
    };
    const englishMarketFallbacks = {
      "코스피": "KOSPI",
      "코스닥": "KOSDAQ",
      "K200 선물": "K200 Futures",
      "선물": "Futures",
      "한국": "Korea",
      "미국": "US",
      "중국": "China",
      "일본": "Japan",
      "유럽": "Europe",
      "동남아": "Southeast Asia",
      "글로벌": "Global",
      "전세계": "Global"
    };
    const englishInvestorFallbacks = {
      "개인": "Retail Investors",
      "외국인": "Foreign Investors",
      "기관합계": "Institutions Total",
      "기관": "Institutions",
      "금융투자": "Financial Investment",
      "보험": "Insurance",
      "투신": "Investment Trusts",
      "사모": "Private Funds",
      "은행": "Banks",
      "기타금융": "Other Financials",
      "연기금": "Pension Funds",
      "기타법인": "Other Corporations"
    };
    const englishFlowMeasureFallbacks = {
      "20일 누적 순매수": "20d Net Buying",
      "순매수": "Net Buying",
      "매수": "Buying",
      "매도": "Selling"
    };
    const englishPhraseFallbacks = [
      ["한국장 마감", "Korea market close"],
      ["미국장 마감", "US market close"],
      ["공포탐욕지수", "Fear & Greed Index"],
      ["경기침체", "Recession"],
      ["시장온도계", "Market Thermometer"],
      ["시장 온도계", "Market Thermometer"],
      ["종합", "Overview"],
      ["수급", "Flows"],
      ["신용·예탁금", "Credit/Cash"],
      ["금리·채권", "Rates/Bonds"],
      ["유동성", "Liquidity"],
      ["원자재·크립토", "Commodities/Crypto"],
      ["심리·변동성", "Sentiment/Volatility"],
      ["밸류에이션", "Valuation"],
      ["캘린더", "Calendar"],
      ["대표주가", "Representative Stocks"],
      ["대표 주가", "Representative Stocks"],
      ["시장지수", "Market Indexes"],
      ["월매출", "Monthly Revenue"],
      ["판매액", "Sales"],
      ["판매량", "Sales Volume"],
      ["매출", "Revenue"],
      ["수출", "Exports"],
      ["가격", "Price"],
      ["기준금리", "Policy Rate"],
      ["국채금리", "Treasury Yield"],
      ["금리차", "Yield Spread"],
      ["회사채", "Corporate Bond"],
      ["하이일드", "High Yield"],
      ["스프레드", "Spread"],
      ["환율", "Exchange Rate"],
      ["유가", "Crude Oil Price"],
      ["철광석", "Iron Ore"],
      ["구리", "Copper"],
      ["알루미늄", "Aluminum"],
      ["리튬", "Lithium"],
      ["배터리", "Battery"],
      ["전력수요", "Power Demand"],
      ["전력 수요", "Power Demand"],
      ["주택착공", "Housing Starts"],
      ["건축허가", "Building Permits"],
      ["미분양 주택", "Unsold Homes"],
      ["주택가격지수", "House Price Index"],
      ["발표", "Release"],
      ["결정", "Decision"],
      ["휴장", "Holiday"],
      ["만기", "Expiry"],
      ["갱신 예정", "Scheduled update"],
      ["갱신", "Update"],
      ["예정", "Scheduled"],
      ["최근", "Recent"],
      ["누적", "Cumulative"],
      ["증가율", "Growth Rate"],
      ["변화율", "Change Rate"],
      ["변화", "Change"],
      ["지표", "Metric"],
      ["흐름", "Trend"],
      ["위험", "Risk"],
      ["주의", "Watch"],
      ["안정", "Stable"],
      ["낮음", "Low"],
      ["보통", "Moderate"],
      ["높음", "High"]
    ];
